
export const projects = [
    {
      title: 'Run Buddy',
      description: "Using HTML and CSS this website showcases a ruuning club.",
        image: '/images/buddy.png',
        tags: ['HTML', 'CSS',],
      source: 'https://google.com',
      code: 'https://github.com/Scuobahia/run-buddy',
      id: 0,
    },
    {
      title: 'Philanthropy-and-me',
      description:"Website for charity purposes. ",
      image: '/images/charity.png',
      tags: ['React','Css', 'JavaScript'],
      source: 'https://google.com',
      code: 'https://github.com/Scuobahia/read-me-generator',
      id: 1,
    },
    {
      title: 'Password Generator',
      description: "Application to randomly generate passwords given certain criteria.",
        image: '/images/password.png',
        tags: ['HTML', 'CSS', 'Javascript'],
      source: 'https://google.com',
      code: 'https://github.com/Scuobahia/password-generator',
      id: 2,
    },
    {
      title: 'Carbon Watchers',
      description: "The Website allows you to keep track of carbon emmisions using an API to receive information dinamically. ",
      image: '/images/carbon.png',
      tags: ['HTML', 'CSS', 'Javascript'],
      source: 'https://google.com',
      code: 'https://github.com/Scuobahia/project-1',
      id: 3,
    },
    {
        title: 'Rate My Rental',
        description: "Take a look at reviews from a property before you rent it. ",
        image: '/images/rental.png',
        tags: ['HTML', 'CSS', 'Javascript', 'Sequelize', 'Node.js'],
        source: 'https://rate-my-rental.herokuapp.com',
        code: 'https://github.com/Scuobahia/rate-my-rental',
        id: 4,
      },
      {
        title: 'Social Network',
        description: " Social Network Media Back end using NoSQL. ",
        image: '/images/social.png',
        tags: ['NoSQL', 'Mongoose', 'Express.js', 'Node.js'],
        source: 'https://google.com',
        code: 'https://github.com/Scuobahia/Social-Network',
        id: 5,
      },
      {
        title: 'Shop More',
        description: "This app helps to organize objects in a database. New objects can be created, updated or deleted by id search. ",
        image: '/images/shop.png',
        tags: ['Javascript', 'Node.Js', 'MySQL', 'Sequelize'],
        source: 'https://google.com',
        code: 'https://github.com/Scuobahia/shop-more',
        id: 6,
      },
      {
        title: 'Tech Blog',
        description: "Save information to a database. While sign in a user can make new posts which are in turn saved for future edit and deletion if one chooses to. ",
        image: '/images/tech.png',
        tags: ['Javacript ', 'Node.js', 'MySQL', 'Sequelize'],
        source:'https://only-tech-news.herokuapp.com',
        code:'https://github.com/Scuobahia/only-tech-news' ,
        id: 7,
      },
  ];
  
  export const TimeLineData = [
  ];